# Generated by Django 5.2.14 on 2026-06-06 20:46

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.filter(owners_phonenumber='+70000000000')

    for flat in flats:
        parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')

        if phonenumbers.is_valid_number(parsed_number):
            flat.owner_pure_phone = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164,
            )
        else:
            flat.owner_pure_phone = None

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(
            normalize_phonenumbers
        ),
    ]
