# Generated by Django 5.2.14 on 2026-06-08 19:37

from django.db import migrations


def transfer_ownership(app, shema_editor):
    Flat = app.get_model('property', 'Flat')
    flats = Flat.objects.all()
    Owner = app.get_model('property', 'Owner')
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):
    
    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_ownership)
    ]
