# Generated by Django 5.2.14 on 2026-06-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20260608_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_flats',
            field=models.ManyToManyField(blank=True, related_name='owner_flats', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
