# Generated by Django 5.2.14 on 2026-06-12 20:22

from django.db import migrations


def link_flats_to_owners(apps, schema_editor):
    Flat = app.get_model('property', 'Flat')
    Owner = app.get_model('property', 'Owner')
    owners = Owner.objects.all()

    for owner in owners:
        flats = Flat.objects.filter(owner=owner.owner)

        owner.owner_flats.set(flats)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_owner_owner_flats'),
    ]

    operations = [
    ]
