# Generated by Django 5.2.15 on 2026-06-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_complaint_complaint_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_full_name',
        ),
    ]
