# Generated by Django 5.2.15 on 2026-06-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_rename_owner_owner_owner_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='normalized_phone',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_flats',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
