# Generated by Django 5.2.15 on 2026-06-21 19:58

from django.db import migrations
import phonenumbers


def normalize_phonenumbers(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')

    for owner in Owner.objects.exclude(phone_number=''):
        parsed_number = phonenumbers.parse(owner.phone_number, 'RU')

        if phonenumbers.is_valid_number(parsed_number):
            owner.normalized_phone = phonenumbers.format_number(
                parsed_number,
                phonenumbers.PhoneNumberFormat.E164,
            )
            owner.save(update_fields=['normalized_phone'])


def reverse_fill_owner_pure_phone(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.update(normalized_phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_rename_owner_full_name_owner_full_name_and_more'),
    ]

    operations = [
        migrations.RunPython(
            normalize_phonenumbers,
            reverse_fill_owner_pure_phone
        ),
    ]

