# Generated by Django 5.2.15 on 2026-06-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_normalize_phone_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_author',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.flat', verbose_name='Квартира, на которую пожаловались'),
        ),
    ]
